export * from "./booking/booking.routes";
export * from "./collection/collection.routes";
export * from "./customer/customer.routes";
export * from "./notification/notification.routes";
export * from "./product/product.routes";
export * from "./setting/setting.routes";
export * from "./staff/staff.routes";
export * from "./staff-schedule/staff-schedule.routes";
export * from "./widget/widget.routes";
