export default {
  id: 5202356076861,
  admin_graphql_api_id: "gid://shopify/Order/5202356076861",
  app_id: 580111,
  browser_ip: "5.195.34.10",
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "a0145134932439f3ea633f25113f8106",
  checkout_id: 36029921395005,
  checkout_token: "f12f77838865f45f5eee0f0512dbf69e",
  client_details: {
    accept_language:
      "en-DK,en;q=0.9,da-DK;q=0.8,da;q=0.7,en-GB;q=0.6,en-US;q=0.5",
    browser_height: 879,
    browser_ip: "5.195.34.10",
    browser_width: 1728,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
  },
  closed_at: null,
  confirmed: true,
  created_at: "2022-11-07T08:19:07+03:00",
  currency: "DKK",
  current_subtotal_price: "180.00",
  current_subtotal_price_set: {
    shop_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
  },
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  current_total_duties_set: null,
  current_total_price: "180.00",
  current_total_price_set: {
    shop_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  customer_locale: "en-DK",
  device_id: null,
  discount_codes: [],
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: null,
  gateway: "bogus",
  landing_site: "/",
  landing_site_ref: null,
  location_id: null,
  merchant_of_record_app_id: null,
  name: "#1012",
  note: "ok\n",
  note_attributes: [],
  number: 12,
  order_number: 1012,
  order_status_url:
    "https://testeriphone.myshopify.com/66323153213/orders/fcba4181cbe9acc5b6c18c6cee8bf1eb/authenticate?key=3a6562f2da8a91add65512bdb62ae9a5",
  original_total_duties_set: null,
  payment_gateway_names: ["bogus"],
  presentment_currency: "DKK",
  processed_at: "2022-11-07T08:19:06+03:00",
  processing_method: "direct",
  reference: null,
  referring_site: "",
  source_identifier: null,
  source_name: "web",
  source_url: null,
  subtotal_price: "180.00",
  subtotal_price_set: {
    shop_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
  },
  tags: "",
  tax_lines: [],
  taxes_included: true,
  test: true,
  token: "fcba4181cbe9acc5b6c18c6cee8bf1eb",
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_line_items_price: "180.00",
  total_line_items_price_set: {
    shop_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
  },
  total_outstanding: "0.00",
  total_price: "180.00",
  total_price_set: {
    shop_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "180.00",
      currency_code: "DKK",
    },
  },
  total_shipping_price_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_tip_received: "0.00",
  total_weight: 0,
  updated_at: "2022-11-07T19:10:06+03:00",
  user_id: null,
  billing_address: {
    province: null,
    country: "Denmark",
    latitude: 56.158596,
    longitude: 10.130378,
    country_code: "DK",
    province_code: null,
  },
  customer: {
    id: 6482301747517,
    accepts_marketing: false,
    created_at: "2022-10-17T18:53:46+03:00",
    updated_at: "2022-11-07T08:19:08+03:00",
    state: "disabled",
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    tags: "",
    currency: "DKK",
    accepts_marketing_updated_at: "2022-10-17T18:53:46+03:00",
    marketing_opt_in_level: null,
    tax_exemptions: [],
    email_marketing_consent: {
      state: "not_subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: null,
    },
    sms_marketing_consent: null,
    admin_graphql_api_id: "gid://shopify/Customer/6482301747517",
    default_address: {
      id: 8942484062525,
      customer_id: 6482301747517,
      company: null,
      province: null,
      country: "Denmark",
      province_code: null,
      country_code: "DK",
      country_name: "Denmark",
      default: true,
    },
  },
  discount_applications: [],
  fulfillments: [],
  line_items: [
    {
      id: 13633324155197,
      admin_graphql_api_id: "gid://shopify/LineItem/13633324155197",
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Makeup",
      price: "90.00",
      price_set: {
        shop_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
      },
      product_exists: true,
      product_id: 7961951273277,
      properties: [
        {
          name: "Staff",
          value:
            '{"staff":"635321e4c8af73a745d192dd","fullname":"jamal soueidan"}',
        },
        {
          name: "Date",
          value: "2022-11-09",
        },
        {
          name: "Hour",
          value: "2022-11-09T13:00:00.000Z",
        },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: true,
      title: "Makeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
      },
      variant_id: 43641561743677,
      variant_inventory_management: null,
      variant_title: "",
      vendor: "testeriphone",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13633324187965,
      admin_graphql_api_id: "gid://shopify/LineItem/13633324187965",
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Makeup",
      price: "90.00",
      price_set: {
        shop_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
      },
      product_exists: true,
      product_id: 7961951273277,
      properties: [
        {
          name: "Staff",
          value:
            '{"staff":"635321e4c8af73a745d192dd","fullname":"jamal soueidan"}',
        },
        {
          name: "Date",
          value: "2022-11-09",
        },
        {
          name: "Hour",
          value: "2022-11-09T11:00:00.000Z",
        },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: true,
      title: "Makeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
      },
      variant_id: 43641561743677,
      variant_inventory_management: null,
      variant_title: "",
      vendor: "testeriphone",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
  ],
  payment_details: {
    credit_card_bin: "1",
    avs_result_code: null,
    cvv_result_code: null,
    credit_card_company: "Bogus",
  },
  payment_terms: null,
  refunds: [],
  shipping_lines: [],
  shop: "testeriphone.myshopify.com",
};
