export default {
  id: 5203342917949,
  admin_graphql_api_id: "gid://shopify/Order/5203342917949",
  app_id: 580111,
  browser_ip: "212.154.66.68",
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "42383a2d3a7fe637265d725f824104d3",
  checkout_id: 36350608703805,
  checkout_token: "659d54cc7bfd0f02c959da7c9aa5f75f",
  client_details: {
    accept_language:
      "en-DK,en;q=0.9,da-DK;q=0.8,da;q=0.7,en-GB;q=0.6,en-US;q=0.5",
    browser_height: 875,
    browser_ip: "212.154.66.68",
    browser_width: 967,
    session_hash: null,
    user_agent: "Shopify CLI",
  },
  closed_at: null,
  confirmed: true,
  created_at: "2022-11-10T15:46:18+03:00",
  currency: "DKK",
  current_subtotal_price: "270.00",
  current_subtotal_price_set: {
    shop_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
  },
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  current_total_duties_set: null,
  current_total_price: "270.00",
  current_total_price_set: {
    shop_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  customer_locale: "en-DK",
  device_id: null,
  discount_codes: [],
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: null,
  gateway: "bogus",
  landing_site: "",
  landing_site_ref: null,
  location_id: null,
  merchant_of_record_app_id: null,
  name: "#1014",
  note: "",
  note_attributes: [],
  number: 14,
  order_number: 1014,
  order_status_url:
    "https://testeriphone.myshopify.com/66323153213/orders/957beaeb8e37b029b0d35ce7f655e649/authenticate?key=249a69d26a17a6dc1a9ae3a638f2e5ee",
  original_total_duties_set: null,
  payment_gateway_names: ["bogus"],
  presentment_currency: "DKK",
  processed_at: "2022-11-10T15:46:17+03:00",
  processing_method: "direct",
  reference: null,
  referring_site: "",
  source_identifier: null,
  source_name: "web",
  source_url: null,
  subtotal_price: "270.00",
  subtotal_price_set: {
    shop_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
  },
  tags: "",
  tax_lines: [],
  taxes_included: true,
  test: true,
  token: "957beaeb8e37b029b0d35ce7f655e649",
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_line_items_price: "270.00",
  total_line_items_price_set: {
    shop_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
  },
  total_outstanding: "0.00",
  total_price: "270.00",
  total_price_set: {
    shop_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "270.00",
      currency_code: "DKK",
    },
  },
  total_shipping_price_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "DKK",
    },
  },
  total_tip_received: "0.00",
  total_weight: 0,
  updated_at: "2022-11-10T15:48:59+03:00",
  user_id: null,
  billing_address: {
    province: null,
    country: "Turkey",
    latitude: null,
    longitude: null,
    country_code: "TR",
    province_code: null,
  },
  customer: {
    id: 6674760237373,
    accepts_marketing: false,
    created_at: "2022-11-10T15:45:43+03:00",
    updated_at: "2022-11-10T15:46:19+03:00",
    state: "disabled",
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    tags: "",
    currency: "DKK",
    accepts_marketing_updated_at: "2022-11-10T15:45:43+03:00",
    marketing_opt_in_level: null,
    tax_exemptions: [],
    email_marketing_consent: {
      state: "not_subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: null,
    },
    sms_marketing_consent: null,
    admin_graphql_api_id: "gid://shopify/Customer/6674760237373",
    default_address: {
      id: 8950728622397,
      customer_id: 6674760237373,
      company: null,
      province: null,
      country: "Turkey",
      province_code: null,
      country_code: "TR",
      country_name: "Turkey",
      default: true,
    },
  },
  discount_applications: [],
  fulfillments: [],
  line_items: [
    {
      id: 13635336044861,
      admin_graphql_api_id: "gid://shopify/LineItem/13635336044861",
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Makeup",
      price: "90.00",
      price_set: {
        shop_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
      },
      product_exists: true,
      product_id: 7961951273277,
      properties: [
        {
          name: "staff",
          value:
            '{"staff":"636b75b68f6e30e6f8686c68","fullname":"Fida Soueidan"}',
        },
        {
          name: "date",
          value: "2022-11-23",
        },
        {
          name: "startHour",
          value: "2022-11-23T14:00:00.000Z",
        },
        {
          name: "endHour",
          value: "2022-11-23T15:00:00.000Z",
        },
        {
          name: "timeZone",
          value: "Europe/Istanbul",
        },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: true,
      title: "Makeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
      },
      variant_id: 43641561743677,
      variant_inventory_management: null,
      variant_title: "",
      vendor: "testeriphone",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13635336077629,
      admin_graphql_api_id: "gid://shopify/LineItem/13635336077629",
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Makeup",
      price: "90.00",
      price_set: {
        shop_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
      },
      product_exists: true,
      product_id: 7961951273277,
      properties: [
        {
          name: "staff",
          value: '{"staff":"636b75a18f6e30e6f8686c63","fullname":"Sara"}',
        },
        {
          name: "date",
          value: "2022-11-10",
        },
        {
          name: "startHour",
          value: "2022-11-10T10:00:00.000Z",
        },
        {
          name: "endHour",
          value: "2022-11-10T11:00:00.000Z",
        },
        {
          name: "timeZone",
          value: "Europe/Istanbul",
        },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: true,
      title: "Makeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
      },
      variant_id: 43641561743677,
      variant_inventory_management: null,
      variant_title: "",
      vendor: "testeriphone",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 13635336110397,
      admin_graphql_api_id: "gid://shopify/LineItem/13635336110397",
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Makeup",
      price: "90.00",
      price_set: {
        shop_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "90.00",
          currency_code: "DKK",
        },
      },
      product_exists: true,
      product_id: 7961951273277,
      properties: [
        {
          name: "staff",
          value:
            '{"staff":"636b75a18f6e30e6f8686c63","fullname":"Sara","anyStaff":true}',
        },
        {
          name: "date",
          value: "2022-11-10",
        },
        {
          name: "startHour",
          value: "2022-11-10T09:00:00.000Z",
        },
        {
          name: "endHour",
          value: "2022-11-10T10:00:00.000Z",
        },
        {
          name: "timeZone",
          value: "Europe/Istanbul",
        },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: true,
      title: "Makeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "DKK",
        },
      },
      variant_id: 43641561743677,
      variant_inventory_management: null,
      variant_title: "",
      vendor: "testeriphone",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
  ],
  payment_details: {
    credit_card_bin: "1",
    avs_result_code: null,
    cvv_result_code: null,
    credit_card_company: "Bogus",
  },
  payment_terms: null,
  refunds: [],
  shipping_lines: [],
};
