export default {
  id: 6709899854141,
  email: "oasdio@asd.dk",
  accepts_marketing: false,
  created_at: "2022-11-18T13:57:00+03:00",
  updated_at: "2022-11-20T00:06:18+03:00",
  first_name: "iodwaioj",
  last_name: "joi",
  orders_count: 0,
  state: "disabled",
  total_spent: "0.00",
  last_order_id: null,
  note: null,
  verified_email: true,
  multipass_identifier: null,
  tax_exempt: false,
  tags: "",
  last_order_name: null,
  currency: "DKK",
  phone: "+4576766767",
  addresses: [
    {
      id: 8991848235325,
      customer_id: 6709899854141,
      first_name: "iodwaioj",
      last_name: "joi",
      company: "",
      city: "BRABRAND",
      province: "",
      country: "Turkey",
      phone: "6767677676",
      name: "iodwaioj joi",
      province_code: null,
      country_code: "TR",
      country_name: "Turkey",
      default: true,
    },
  ],
  accepts_marketing_updated_at: "2022-11-18T13:57:00+03:00",
  marketing_opt_in_level: null,
  tax_exemptions: [],
  email_marketing_consent: {
    state: "not_subscribed",
    opt_in_level: "single_opt_in",
    consent_updated_at: null,
  },
  sms_marketing_consent: {
    state: "not_subscribed",
    opt_in_level: "single_opt_in",
    consent_updated_at: null,
    consent_collected_from: "SHOPIFY",
  },
  admin_graphql_api_id: "gid://shopify/Customer/6709899854141",
  default_address: {
    id: 8991848235325,
    customer_id: 6709899854141,
    first_name: "iodwaioj",
    last_name: "joi",
    company: "",
    city: "BRABRAND",
    province: "",
    country: "Turkey",
    phone: "6767677676",
    name: "iodwaioj joi",
    province_code: null,
    country_code: "TR",
    country_name: "Turkey",
    default: true,
  },
};
